<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>13</LangVersion>
		<CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
		<IsRoslynComponent>true</IsRoslynComponent>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
		<Nullable>enable</Nullable>
		<NoWarn>$(NoWarn);NU5128</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<AdditionalFiles Include="AnalyzerReleases.Shipped.md" />
		<AdditionalFiles Include="AnalyzerReleases.Unshipped.md" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Namotion.Interceptor.Generator.Tests" />
	</ItemGroup>

	<PropertyGroup>
		<IncludeBuildOutput>false</IncludeBuildOutput>
	</PropertyGroup>

	<ItemGroup>
		<None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="4.14.0" PrivateAssets="all" />
	</ItemGroup>
</Project>
