using System.Linq;
using System.Text;
using Namotion.Interceptor.Generator.Models;

namespace Namotion.Interceptor.Generator;

internal static class SubjectCodeGenerator
{
    /// <summary>
    /// Generates the C# code for an interceptor subject class.
    /// </summary>
    public static string Generate(SubjectMetadata metadata)
    {
        var builder = new StringBuilder();

        EmitFileHeader(builder);
        EmitNamespaceOpening(builder, metadata.NamespaceName);
        EmitContainingTypeOpening(builder, metadata.ContainingTypes);
        EmitClassDeclaration(builder, metadata);
        EmitNotifyPropertyChangedImplementation(builder, metadata);
        EmitInterceptorSubjectImplementation(builder, metadata);
        EmitDefaultProperties(builder, metadata);
        EmitConstructors(builder, metadata);
        EmitProperties(builder, metadata);
        EmitMethods(builder, metadata);
        EmitHelperMethods(builder, metadata);
        EmitClassClosing(builder);
        EmitContainingTypeClosing(builder, metadata.ContainingTypes);
        EmitNamespaceClosing(builder, metadata.NamespaceName);

        return builder.ToString();
    }

    /// <summary>
    /// The accessibility of a member that a generated subclass has to reach. A sealed class cannot be
    /// derived from, so a protected member in one is CS0628, which is a build error under
    /// TreatWarningsAsErrors; nothing can need the access, so emit private instead.
    /// </summary>
    private static string ProtectedUnlessSealed(SubjectMetadata metadata) => metadata.IsSealed ? "private" : "protected";

    /// <summary>
    /// Emitted per member rather than across the block: a blanket 'new' is CS0109 wherever nothing is
    /// hidden, and an NI0012 base that hides nothing is the common case. Names come from
    /// <see cref="MemberNames"/>, never from a literal here.
    /// </summary>
    private static string HidingModifier(SubjectMetadata metadata, string memberName)
        => metadata.BaseClass.HiddenMemberNames.Contains(memberName) ? "new " : "";

    /// <summary>
    /// Generates the filename for the generated code.
    /// </summary>
    public static string GetFileName(SubjectMetadata metadata)
    {
        // From the symbol name, not from the emitted names: those keep their source spelling, and
        // AddSource rejects the '@' of a keyword escape, the backslash of a \uXXXX escape, and the
        // comment or line break a namespace name can hold, failing the whole subject with NI0004
        // and emitting nothing. The symbol name is that name normalised, so only two decorations go.
        return metadata.FullTypeName
            .Replace("global::", "")
            .Replace("@", "") + ".g.cs";
    }

    private static void EmitFileHeader(StringBuilder builder)
    {
        builder.Append("""
            // <auto-generated>
            //     This code was generated by Namotion.Interceptor.Generator
            // </auto-generated>

            using Namotion.Interceptor;
            using Namotion.Interceptor.Interceptors;

            using System;
            using System.Collections.Concurrent;
            using System.Collections.Generic;
            using System.Collections.Frozen;
            using System.ComponentModel;
            using System.Linq;
            using System.Reflection;
            using System.Runtime.CompilerServices;
            using System.Text.Json.Serialization;

            #pragma warning disable CS8669
            #pragma warning disable CS0649
            #pragma warning disable CS0067
            #pragma warning disable CS9193


            """);
    }

    private static void EmitNamespaceOpening(StringBuilder builder, string? namespaceName)
    {
        if (namespaceName is null)
        {
            return;
        }

        builder.AppendLine($"namespace {namespaceName}");
        builder.AppendLine("{");
    }

    private static void EmitNamespaceClosing(StringBuilder builder, string? namespaceName)
    {
        if (namespaceName is null)
        {
            return;
        }

        builder.AppendLine("}");
    }

    private static void EmitContainingTypeOpening(StringBuilder builder, ContainingType[] containingTypes)
    {
        foreach (var containingType in containingTypes)
        {
            builder.AppendLine($"    partial {containingType.Keyword} {containingType.Name}");
            builder.AppendLine("    {");
        }
    }

    private static void EmitContainingTypeClosing(StringBuilder builder, ContainingType[] containingTypes)
    {
        foreach (var _ in containingTypes)
        {
            builder.AppendLine("    }");
        }
    }

    private static void EmitClassDeclaration(StringBuilder builder, SubjectMetadata metadata)
    {
        var interfaces = metadata.BaseClass.HasInpc
            ? "IInterceptorSubject"
            : "IInterceptorSubject, INotifyPropertyChanged, IRaisePropertyChanged";

        builder.AppendLine($"    {metadata.AccessModifier} partial class {metadata.ClassName} : {interfaces}");
        builder.AppendLine("    {");
    }

    private static void EmitClassClosing(StringBuilder builder)
    {
        builder.AppendLine("    }");
    }

    private static void EmitNotifyPropertyChangedImplementation(StringBuilder builder, SubjectMetadata metadata)
    {
        if (metadata.BaseClass.HasInpc)
        {
            return;
        }

        builder.AppendLine($"        {HidingModifier(metadata, MemberNames.PropertyChanged)}public event PropertyChangedEventHandler? PropertyChanged;");
        builder.AppendLine();
        builder.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        builder.AppendLine($"        {HidingModifier(metadata, MemberNames.RaisePropertyChanged)}{ProtectedUnlessSealed(metadata)} void RaisePropertyChanged(string propertyName) => PropertyChanged?.Invoke(this, PropertyChangedEventArgsCache.Get(propertyName));");
        builder.AppendLine();
        builder.AppendLine("        void IRaisePropertyChanged.RaisePropertyChanged(string propertyName) => RaisePropertyChanged(propertyName);");
        builder.AppendLine();
    }

    private static void EmitInterceptorSubjectImplementation(StringBuilder builder, SubjectMetadata metadata)
    {
        // Emitted by every subject, root and derived alike. It is the one member that cannot move
        // to the root: DefaultProperties is a static hidden by 'new' at each level, so this
        // expression binds at compile time to the class it was emitted into. Emitted only in the
        // root, every derived subject would report the root's property set.
        if (!metadata.BaseClass.EmitsInterceptionMembers)
        {
            builder.AppendLine("        [JsonIgnore]");
            builder.AppendLine("        IReadOnlyDictionary<string, SubjectPropertyMetadata> IInterceptorSubject.Properties => GetInstanceProperties() ?? DefaultProperties;");
            builder.AppendLine();
            return;
        }

        builder.AppendLine("        private IInterceptorExecutor? _context;");
        builder.AppendLine("        private IReadOnlyDictionary<string, SubjectPropertyMetadata>? _properties;");
        builder.AppendLine();
        builder.AppendLine("        [JsonIgnore]");
        builder.AppendLine("        IInterceptorSubjectContext IInterceptorSubject.Context => InterceptorExecutor.GetOrCreate(ref _context, this);");
        builder.AppendLine();
        builder.AppendLine("        [JsonIgnore]");
        builder.AppendLine("        ConcurrentDictionary<(string? property, string key), object?> IInterceptorSubject.Data { get; } = new();");
        builder.AppendLine();
        builder.AppendLine("        [JsonIgnore]");
        builder.AppendLine("        IReadOnlyDictionary<string, SubjectPropertyMetadata> IInterceptorSubject.Properties => GetInstanceProperties() ?? DefaultProperties;");
        builder.AppendLine();
        builder.AppendLine("        [JsonIgnore]");
        builder.AppendLine("        object IInterceptorSubject.SyncRoot { get; } = new object();");
        builder.AppendLine();
        builder.AppendLine("        void IInterceptorSubject.AddProperties(params IEnumerable<SubjectPropertyMetadata> properties)");
        builder.AppendLine("        {");
        builder.AppendLine("            lock (((IInterceptorSubject)this).SyncRoot)");
        builder.AppendLine("            {");
        // Dispatching through the interface rather than reading _properties directly is what lets
        // this method live in the root: it makes the merge start from the most derived
        // DefaultProperties instead of this class's own.
        builder.AppendLine("                _properties = ((IInterceptorSubject)this).Properties");
        builder.AppendLine("                    .Concat(properties.Select(p => new KeyValuePair<string, SubjectPropertyMetadata>(p.Name, p)))");
        builder.AppendLine("                    .ToFrozenDictionary();");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
    }

    private static void EmitDefaultProperties(StringBuilder builder, SubjectMetadata metadata)
    {
        var newModifier = metadata.BaseClass.TypeName is not null ? "new " : "";

        builder.AppendLine($"        public {newModifier}static IReadOnlyDictionary<string, SubjectPropertyMetadata> DefaultProperties {{ get; }} =");
        builder.AppendLine("            new Dictionary<string, SubjectPropertyMetadata>");
        builder.AppendLine("            {");

        // Each entry below is emitted as an indexer assignment (["Name"] = ...) rather than a
        // collection-initializer Add(...), so a duplicate key silently overwrites the earlier entry
        // instead of throwing at type-init. The extractor already dedups property names and reports
        // NI0008 on a genuine collision, so this should never trigger today, but the trade-off is
        // worth keeping in mind: a future extractor bug that lets a duplicate through would silently
        // drop a property here rather than fail loudly.
        foreach (var property in metadata.Properties)
        {
            // An explicitly implemented member is unreachable through the class, so it is emitted
            // through the interface exactly like an interface default property.
            var accessorInterfaceTypeName = property.IsFromInterface
                ? property.InterfaceTypeName
                : property.ExplicitInterfaceTypeName;

            if (accessorInterfaceTypeName is not null)
            {
                var getterLambda = property.HasGetter
                    ? $"(o) => (({accessorInterfaceTypeName})o).{property.Name}"
                    : "null";
                var setterLambda = property.HasSetter
                    ? $"(o, v) => (({accessorInterfaceTypeName})o).{property.Name} = ({property.FullTypeName})v"
                    : "null";

                builder.AppendLine($"                    [\"{property.Name}\"] = new SubjectPropertyMetadata(");
                builder.AppendLine($"                        typeof({accessorInterfaceTypeName}).GetProperty(nameof({accessorInterfaceTypeName}.{property.Name}), BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance)!,");
                builder.AppendLine($"                        {getterLambda},");
                builder.AppendLine($"                        {setterLambda},");
                builder.AppendLine("                        isIntercepted: false,");
                builder.AppendLine("                        isDynamic: false),");
            }
            else
            {
                var getterLambda = property.HasGetter
                    ? $"(o) => (({metadata.ClassName})o).{property.Name}"
                    : "null";
                // Note: init-only properties cannot have a setter lambda because they can only be set during construction
                var setterLambda = property.HasSetter
                    ? $"(o, v) => (({metadata.ClassName})o).{property.Name} = ({property.FullTypeName})v"
                    : "null";

                builder.AppendLine($"                    [\"{property.Name}\"] = new SubjectPropertyMetadata(");
                builder.AppendLine($"                        typeof({metadata.ClassName}).GetProperty(nameof({property.Name}), BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance)!,");
                builder.AppendLine($"                        {getterLambda},");
                builder.AppendLine($"                        {setterLambda},");
                builder.AppendLine($"                        isIntercepted: {(property.IsPartial ? "true" : "false")},");
                builder.AppendLine("                        isDynamic: false),");
            }
        }

        builder.AppendLine("            }");

        if (metadata.BaseClass.TypeName is not null)
        {
            builder.AppendLine($"            .Concat({metadata.BaseClass.TypeName}.DefaultProperties)");
        }

        builder.AppendLine("            .ToFrozenDictionary();");
        builder.AppendLine();
    }

    /// <summary>
    /// Fully qualified rather than imported, so generated files of subjects without the attribute stay
    /// byte-identical, and rooted at global:: so the name still reaches a consumer-declared polyfill
    /// when the subject's own namespace shadows System.
    /// </summary>
    private static void EmitSetsRequiredMembersAttribute(StringBuilder builder, SubjectMetadata metadata)
    {
        if (metadata.ParameterlessConstructorSetsRequiredMembers)
        {
            builder.AppendLine("        [global::System.Diagnostics.CodeAnalysis.SetsRequiredMembers]");
        }
    }

    private static void EmitConstructors(StringBuilder builder, SubjectMetadata metadata)
    {
        // Generate parameterless constructor only if no constructor exists
        if (metadata.NeedsGeneratedParameterlessConstructor)
        {
            EmitSetsRequiredMembersAttribute(builder, metadata);
            builder.AppendLine($"        public {metadata.ClassName}()");
            builder.AppendLine("        {");
            builder.AppendLine("        }");
            builder.AppendLine();
        }

        // Generate constructor with context parameter if we have or will have a parameterless constructor
        if (metadata.HasOrWillHaveParameterlessConstructor)
        {
            EmitSetsRequiredMembersAttribute(builder, metadata);
            builder.AppendLine($"        public {metadata.ClassName}(IInterceptorSubjectContext context) : this()");
            builder.AppendLine("        {");
            builder.AppendLine("            ((IInterceptorSubject)this).Context.AddFallbackContext(context);");
            builder.AppendLine("        }");
            builder.AppendLine();
        }
    }

    private static void EmitProperties(StringBuilder builder, SubjectMetadata metadata)
    {
        foreach (var property in metadata.Properties.Where(p => p.IsPartial))
        {
            EmitProperty(builder, property, metadata);
        }
    }

    private static void EmitProperty(StringBuilder builder, PropertyMetadata property, SubjectMetadata metadata)
    {
        // Backing field
        builder.AppendLine($"        private {property.FullTypeName} _{property.Name};");
        builder.AppendLine();

        // Every modifier the declaring half carries has to be repeated here, or the two halves of
        // the partial property disagree and the compiler reports CS8800. 'new' matters beyond
        // symmetry: it is the only way to silence the CS0108 that accompanies NI0005.
        var additionalModifiers = "";
        if (property.IsNew)
        {
            additionalModifiers += "new ";
        }

        if (property.IsVirtual)
        {
            additionalModifiers += "virtual ";
        }

        if (property.IsSealed)
        {
            additionalModifiers += "sealed ";
        }

        if (property.IsOverride)
        {
            additionalModifiers += "override ";
        }

        var requiredModifier = property.IsRequired ? "required " : "";

        builder.AppendLine($"        {property.AccessModifier} {requiredModifier}{additionalModifiers}partial {property.FullTypeName} {property.Name}");
        builder.AppendLine("        {");

        // Getter
        if (property.HasGetter)
        {
            var getterModifiers = property.GetterAccessModifier is not null ? $"{property.GetterAccessModifier} " : "";
            builder.AppendLine($"            {getterModifiers}get");
            builder.AppendLine("            {");
            builder.AppendLine($"                return GetPropertyValue<{property.FullTypeName}>(nameof({property.Name}), static (o) => (({metadata.ClassName})o)._{property.Name});");
            builder.AppendLine("            }");
        }

        // Setter or Init
        if (property.HasSetter || property.HasInit)
        {
            var accessorText = property.HasInit ? "init" : "set";
            var setterModifiers = property.SetterAccessModifier is not null ? $"{property.SetterAccessModifier} " : "";

            // Determine how to call RaisePropertyChanged:
            // - [InterceptorSubject] base with a callable member: direct call (fastest); the attribute
            //   alone does not prove one exists, see SubjectAncestry.HasCallableRaisePropertyChanged
            // - Manual IRaisePropertyChanged base: interface cast (rare case)
            // - Own implementation: direct call to own method (fastest)
            var raisePropertyChangedCall =
                metadata.BaseClass.HasInterceptorSubject && metadata.BaseClass.HasCallableRaisePropertyChanged
                    ? $"RaisePropertyChanged(nameof({property.Name}))"
                    : metadata.BaseClass.HasInpc
                        ? $"((IRaisePropertyChanged)this).RaisePropertyChanged(nameof({property.Name}))"
                        : $"RaisePropertyChanged(nameof({property.Name}))";

            builder.AppendLine($"            {setterModifiers}{accessorText}");
            builder.AppendLine("            {");
            builder.AppendLine("                var newValue = value;");
            builder.AppendLine("                var cancel = false;");
            builder.AppendLine($"                On{property.Name}Changing(ref newValue, ref cancel);");
            builder.AppendLine($"                if (!cancel && SetPropertyValue(nameof({property.Name}), newValue, _{property.Name}, static (o, v) => (({metadata.ClassName})o)._{property.Name} = v))");
            builder.AppendLine("                {");
            builder.AppendLine($"                    On{property.Name}Changed(_{property.Name});");
            builder.AppendLine($"                    {raisePropertyChangedCall};");
            builder.AppendLine("                }");
            builder.AppendLine("            }");
        }

        builder.AppendLine("        }");
        builder.AppendLine();

        // Partial method hooks
        if (property.HasSetter || property.HasInit)
        {
            builder.AppendLine($"        partial void On{property.Name}Changing(ref {property.FullTypeName} newValue, ref bool cancel);");
            builder.AppendLine();
            builder.AppendLine($"        partial void On{property.Name}Changed({property.FullTypeName} newValue);");
            builder.AppendLine();
        }
    }

    private static void EmitMethods(StringBuilder builder, SubjectMetadata metadata)
    {
        foreach (var method in metadata.Methods)
        {
            EmitMethod(builder, method, metadata);
        }
    }

    private static void EmitMethod(StringBuilder builder, MethodMetadata method, SubjectMetadata metadata)
    {
        var parameterDeclarations = string.Join(", ", method.Parameters.Select(p => $"{p.Type} {p.Name}"));
        var directParameterCode = string.Join(", ", method.Parameters.Select((p, i) => $"({p.Type})p[{i}]!"));
        var invokeParameterCode = method.Parameters.Any()
            ? ", " + string.Join(", ", method.Parameters.Select(p => p.Name))
            : "";

        if (method.ReturnType != "void")
        {
            builder.AppendLine($"        public {method.ReturnType} {method.Name}({parameterDeclarations})");
            builder.AppendLine("        {");
            builder.AppendLine($"            return ({method.ReturnType})InvokeMethod(\"{method.Name}\", static (s, p) => (({metadata.ClassName})s).{method.FullMethodName}({directParameterCode}){invokeParameterCode})!;");
            builder.AppendLine("        }");
        }
        else
        {
            builder.AppendLine($"        public {method.ReturnType} {method.Name}({parameterDeclarations})");
            builder.AppendLine("        {");
            builder.AppendLine($"            InvokeMethod(\"{method.Name}\", static (s, p) => {{ (({metadata.ClassName})s).{method.FullMethodName}({directParameterCode}); return null; }}{invokeParameterCode});");
            builder.AppendLine("        }");
        }

        builder.AppendLine();
    }

    private static void EmitHelperMethods(StringBuilder builder, SubjectMetadata metadata)
    {
        if (!metadata.BaseClass.EmitsInterceptionMembers)
        {
            return;
        }

        var modifier = ProtectedUnlessSealed(metadata);

        // A method rather than a property: DynamicSubjectFactory reflects over
        // GetProperties(Instance | Public | NonPublic), which returns inherited protected
        // properties and turns every unknown one into an intercepted subject property. A protected
        // property here would give every Castle-proxied generated subject a phantom property.
        builder.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        builder.AppendLine($"        {HidingModifier(metadata, MemberNames.GetInstanceProperties)}{modifier} IReadOnlyDictionary<string, SubjectPropertyMetadata>? GetInstanceProperties() => _properties;");
        builder.AppendLine();
        builder.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        builder.AppendLine($"        {HidingModifier(metadata, MemberNames.GetPropertyValue)}{modifier} TProperty GetPropertyValue<TProperty>(string propertyName, Func<IInterceptorSubject, TProperty> readValue)");
        builder.AppendLine("        {");
        builder.AppendLine("            return _context is not null ? _context.GetPropertyValue(propertyName, readValue)! : readValue(this)!;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        builder.AppendLine($"        {HidingModifier(metadata, MemberNames.SetPropertyValue)}{modifier} bool SetPropertyValue<TProperty>(string propertyName, TProperty newValue, TProperty currentValue, Action<IInterceptorSubject, TProperty> setValue)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (_context is null)");
        builder.AppendLine("            {");
        builder.AppendLine("                setValue(this, newValue);");
        builder.AppendLine("                return true;");
        builder.AppendLine("            }");
        builder.AppendLine("            else");
        builder.AppendLine("            {");
        builder.AppendLine("                return _context.SetPropertyValue(propertyName, newValue, currentValue, setValue);");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        builder.AppendLine($"        {HidingModifier(metadata, MemberNames.InvokeMethod)}{modifier} object? InvokeMethod(string methodName, Func<IInterceptorSubject, object?[], object?> invokeMethod, params object?[] parameters)");
        builder.AppendLine("        {");
        builder.AppendLine("            return _context is not null ? _context.InvokeMethod(methodName, parameters, invokeMethod) : invokeMethod(this, parameters);");
        builder.AppendLine("        }");
    }
}
